apiVersion: v1
kind: Service
metadata:
  name: todo-api-service
  namespace: todo-api
  labels:
    app: todo-api
spec:
  type: LoadBalancer
  selector:
    app: todo-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
